library(stringr)
t0 <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/shiny_reactive_MSc/shiny_processed_data/PCA_time_point/t0_PCA.csv', header = F)
t24 <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/shiny_reactive_MSc/shiny_processed_data/PCA_time_point/t24_pca.csv', header = F)
meta_name <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/shiny_reactive_MSc/final_use_csv/full_data/meta_comp_name.csv')
gene_name <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/shiny_reactive_MSc/final_use_csv/full_data/ngs_gene_name.csv', colClasses=c(NA, NA))
gene_name_temp <-str_replace(gene_name$ID, "-", ".")
gene_name_temp<- as.data.frame(gene_name_temp)
gene_name <- cbind(gene_name_temp,gene_name$gene)
meta_data_24 <- merge(t24, meta_name, by.x = 1, by.y = 1)
gene_data_24 <- merge(t24, gene_name ,by.x = 1, by.y = 1)
names(meta_data_24)[2]<- paste('v2')
names(gene_data_24)[2]<- paste('v2')
final_data_24 <- rbind (meta_data_24,gene_data_24)
final_data_24 <- na.omit(final_data_24)


meta_data_0 <- merge(t0, meta_name, by.x = 1, by.y = 1)
gene_data_0 <- merge(t0, gene_name ,by.x = 1, by.y = 1)
names(meta_data_0)[2]<- paste('v2')
names(gene_data_0)[2]<- paste('v2')
final_data_0 <- rbind (meta_data_0,gene_data_0)
final_data_0 <- na.omit(final_data_0)

write.csv(final_data_24,'/home/florence/Documents/Bioinformatics_MSc/Project/shiny_reactive_MSc/shiny_processed_data/PCA_time_point/pca_t24_loadings.csv')
write.csv(final_data_0,'/home/florence/Documents/Bioinformatics_MSc/Project/shiny_reactive_MSc/shiny_processed_data/PCA_time_point/pca_t0_loadings.csv')
