t24 <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/shiny_processed_data/t24_pca.csv', header = F)
meta_name <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/final_use_csv/meta_comp_name.csv')
gene_name <- read.csv('/home/florence/Documents/Bioinformatics_MSc/Project/final_use_csv/ngs_gene_name.csv', colClasses=c(NA, NA))
gene_name_temp <-str_replace(gene_name$ID, "-", ".")
gene_name_temp<- as.data.frame(gene_name_temp)
gene_name <- cbind(gene_name_temp,gene_name$gene)
meta_data <- merge(t24, meta_name, by.x = 1, by.y = 1)
gene_data <- merge(t24, gene_name ,by.x = 1, by.y = 1)
names(meta_data)[2]<- paste('v2')
names(gene_data)[2]<- paste('v2')
final_data <- rbind (meta_data,gene_data)
final_data <- na.omit(final_data)
